spring:
  datasource:
    url: jdbc:postgresql://192.168.0.7:5432/demo_db   # ← VM IP에 맞춰 수정
    username: demo_user
    password: '03474506'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update      # 개발 단계용. 운영은 none + Flyway/Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
logging:
  level:
    org.springframework.security: debug