spring:
  session:
    store-type: redis
    timeout: 30m

  data:
    redis:
      host: 192.168.0.15
      port: 6379

  datasource:
    users:
      jdbc-url: ${SPRING_DATASOURCE_USERS_URL}
      username: ${SPRING_DATASOURCE_USERS_USERNAME}
      password: ${SPRING_DATASOURCE_USERS_PASSWORD}
      driver-class-name: org.postgresql.Driver
    posts:
      jdbc-url: ${SPRING_DATASOURCE_POSTS_URL}
      username: ${SPRING_DATASOURCE_POSTS_USERNAME}
      password: ${SPRING_DATASOURCE_POSTS_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        # 운영은 none + Flyway/Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

management:
  # management.server.port: 9091   # 메인 포트와 분리하고 싶으면 주석 해제
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.security: debug